name: Build and Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run build in Debian 12 container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace debian:12-slim bash -c \
          "sed -i 's/sudo //g' /workspace/build.sh && chmod +x /workspace/build.sh && /workspace/build.sh"

      - name: Collect build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            /workspace/output/*.deb
